-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE PUBLIC."DimDate" ("Date_id" bigint NOT NULL,
																																MONTH bigint, MONTH_NAME CHARACTER varying, DAY bigint, WEEKDAY CHARACTER varying, YEAT bigint, PRIMARY KEY ("Date_id"));


CREATE TABLE PUBLIC."DimCategory" ("Category_id" bigint NOT NULL,
																																				"Category_name" CHARACTER varying, PRIMARY KEY ("Category_id"));


CREATE TABLE PUBLIC."Dimitem" (ITEM_ID bigint NOT NULL,
																																ITEM_NAME CHARACTER varying, PRIMARY KEY (ITEM_ID));


CREATE TABLE PUBLIC."DimCountry" ("Country_id" bigint NOT NULL,
																																			"Country_name" CHARACTER varying, PRIMARY KEY ("Country_id"));


CREATE TABLE PUBLIC."FactSales" (ORDER_ID bigint NOT NULL,
																																		"Date_id" bigint, "Country_id" bigint, "Category_id" bigint, ITEM_ID bigint, PRIMARY KEY (ORDER_ID));


ALTER TABLE PUBLIC."FactSales" ADD
FOREIGN KEY ("Date_id") REFERENCES PUBLIC."DimDate" ("Date_id") NOT VALID;


ALTER TABLE PUBLIC."FactSales" ADD
FOREIGN KEY ("Country_id") REFERENCES PUBLIC."DimCountry" ("Country_id") NOT VALID;


ALTER TABLE PUBLIC."FactSales" ADD
FOREIGN KEY ("Category_id") REFERENCES PUBLIC."DimCategory" ("Category_id") NOT VALID;


ALTER TABLE PUBLIC."FactSales" ADD
FOREIGN KEY (ITEM_ID) REFERENCES PUBLIC."Dimitem" (ITEM_ID) NOT VALID;

END;